[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/site-web/index.html"
to = "/tous-les-outils/site-web/"

[[redirects]]
from = "/equipe-editoriale/index.html"
to = "/equipe/equipe-editoriale/"

[[redirects]]
from = "/parcours/communication-numerique-et-design-dexperience/index.html"
to = "/parcours/strategie-de-communication-numerique-et-design-d-experience/"

[[redirects]]
from = "/medium/index.html"
to = "/tous-les-outils/medium/"

[[redirects]]
from = "/github/index.html"
to = "/tous-les-outils/github/"

[[redirects]]
from = "/twitter-x/index.html"
to = "/tous-les-outils/twitter-x/"

[[redirects]]
from = "/malt/index.html"
to = "/tous-les-outils/malt/"

[[redirects]]
from = "/behance/index.html"
to = "/tous-les-outils/behance/"

[[redirects]]
from = "/instagram/index.html"
to = "/tous-les-outils/instagram/"

[[redirects]]
from = "/vimeo/index.html"
to = "/tous-les-outils/vimeo/"

[[redirects]]
from = "/dribbble/index.html"
to = "/tous-les-outils/dribbble/"

[[redirects]]
from = "/linkedin/index.html"
to = "/tous-les-outils/linkedin/"

